---
abstract: 'Powerful fast feature-rich Perl source code profiler'
author:
  - 'Tim Bunce <timb@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  ExtUtils::MakeMaker: '0'
  Sub::Name: '0.11'
  Test::Differences: '0.60'
  Test::More: '0.84'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-NYTProf
no_index:
  directory:
    - t
    - inc
  package:
    - SVG
requires:
  File::Which: '1.09'
  Getopt::Long: '0'
  JSON::MaybeXS: '0'
  List::Util: '0'
  XSLoader: '0'
resources:
  MailingList: http://groups.google.com/group/develnytprof-dev
  bugtracker: https://github.com/timbunce/devel-nytprof/issues
  homepage: https://code.google.com/p/perl-devel-nytprof/
  license: http://dev.perl.org/licenses/
  repository: https://github.com/timbunce/devel-nytprof.git
version: '6.14'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
